@startuml





          class TestHistory {
            + TestRepository testRepository
            + ResultRepository resultRepository
            + Test test
            + QuestionRepository questionRepository
            + RoomRepository roomRepository

            + void onCreate(Bundle savedInstanceState)
            + void onBackButtonClickk(View view)
          }

          class Authentication {
            + static Student getStudent()
            + static Teacher getTeacher()
          }

          class Student {
            - String id
            - String firstName
            - String lastName
            - String groupNumber
            - String password
            - String email
            - String profilePicture

            + Student(String id, String firstName, String lastName, String groupNumber, String password, String email, String profilePicture)
            + String getId()
          }

         

          class ResultRepository {
            + ResultRepository(FirebaseFirestore db)
            + CompletableFuture<List<Result>> getAllResultByStudentId(String studentId)
          }

          class TestRepository {
            + TestRepository(FirebaseFirestore db)
            + CompletableFuture<List<Test>> getAllTestByResult(List<Result> result)
            + CompletableFuture<List<Test>> getAllTestByStudentId(String studentId)
            + CompletableFuture<List<Test>> getAllTestByTeacherId(String teacherId)
          }

          class QuestionRepository {
            + QuestionRepository(FirebaseFirestore db)
          }

          class RoomRepository {
            + RoomRepository(FirebaseFirestore db)
          }

          class FirebaseFirestore {
            + static FirebaseFirestore getInstance()
          }

          class TestAdapter {
            + TestAdapter(List<Test> testList, Context context)
          }

          class Test {
            - String id
            - String title
            - String description

            + Test(String id, String title, String description)
            + String getId()
          }

          class Result {
            - String id
            - String studentId
            - String testId

            + Result(String id, String studentId, String testId)
            + String getTestId()
          }

          TestHistory "1" -right-> "1" Authentication
          TestHistory "1" -right-> "1" ResultRepository
          TestHistory "1" -right-> "1" TestRepository
          TestHistory "1" -down-> "1" QuestionRepository
          TestHistory "1" -down-> "1" RoomRepository
          ResultRepository "1" -down-> "1" FirebaseFirestore
          TestRepository "1" -down-> "1" FirebaseFirestore
          QuestionRepository "1" -down-> "1" FirebaseFirestore
          RoomRepository "1" -down-> "1" FirebaseFirestore
          TestHistory "1" -down-> "1" RecyclerView
          RecyclerView "1" -down-> "1" TestAdapter
          TestAdapter "1" -down-> "1" Test
          Result "1" -down-> "1" Student
          Result "1" -down-> "1" Test



}


@enduml
